# Generated by Django 4.0.5 on 2022-06-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_books_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='date_published',
        ),
    ]
