# Generated by Django 4.0.5 on 2022-06-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_books_date_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='delete_flag',
        ),
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('1', 'Available'), ('2', 'Not Available')], default=1, max_length=2),
        ),
    ]
